/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;




/**
 *
 * @author Antonio
 */
public class Cliente extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Cliente() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_agrofacil = new javax.swing.JPanel();
        cliente = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ingresar_cedula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ingresar_apellido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ingresar_nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        ingresar_telefono = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        ingresar_direccion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        ingresar_email = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        panel_agregar = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_buscar = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_modificar = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_mostrar = new javax.swing.JPanel();
        mostrar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agrofacil.setBackground(new java.awt.Color(0, 204, 0));
        panel_agrofacil.setLayout(null);

        cliente.setFont(new java.awt.Font("Leelawadee UI", 3, 48)); // NOI18N
        cliente.setForeground(new java.awt.Color(255, 255, 255));
        cliente.setText("CLIENTE");
        panel_agrofacil.add(cliente);
        cliente.setBounds(290, 20, 240, 64);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login1.png"))); // NOI18N
        panel_agrofacil.add(icono);
        icono.setBounds(680, 10, 107, 95);

        add(panel_agrofacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        cedula.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cedula.setText("CEDULA DE CIUDADANIA");
        add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        apellido.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        apellido.setText("APELLIDO DEL CLIENTE");
        add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        nombre.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombre.setText(" NOMBRE DEL CLIENTE");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 140, -1, -1));

        telefono.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        telefono.setText("TELÉFONO DEL CLIENTE");
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        direccion.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        direccion.setText("DIRECCIÓN DEL CLIENTE");
        add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        email.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        email.setText(" E-MAIL DEL CLIENTE");
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 190, -1));

        ingresar_cedula.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_cedula.setText("Ingresar numero de cedula");
        ingresar_cedula.setBorder(null);
        ingresar_cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_cedulaMousePressed(evt);
            }
        });
        add(ingresar_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 150, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 270, 10));

        ingresar_apellido.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_apellido.setText("Ingresar apellidos completos");
        ingresar_apellido.setBorder(null);
        ingresar_apellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_apellidoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_apellidoMousePressed(evt);
            }
        });
        ingresar_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_apellidoActionPerformed(evt);
            }
        });
        add(ingresar_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 250, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 270, 10));

        ingresar_nombre.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_nombre.setText("Ingresar nombre completo");
        ingresar_nombre.setBorder(null);
        ingresar_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_nombreMousePressed(evt);
            }
        });
        add(ingresar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 10));

        ingresar_telefono.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_telefono.setText("Ingresar el numero de teléfono");
        ingresar_telefono.setBorder(null);
        ingresar_telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_telefonoMousePressed(evt);
            }
        });
        add(ingresar_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 270, 10));

        ingresar_direccion.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_direccion.setText("Ingresar direccion de residencia");
        ingresar_direccion.setBorder(null);
        ingresar_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_direccionMousePressed(evt);
            }
        });
        add(ingresar_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 270, 10));

        ingresar_email.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_email.setText("Ingresar @email");
        ingresar_email.setBorder(null);
        ingresar_email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_emailMousePressed(evt);
            }
        });
        add(ingresar_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 120, 30));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 270, 10));

        panel_agregar.setBackground(new java.awt.Color(51, 204, 0));
        panel_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_agregarMouseExited(evt);
            }
        });

        agregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 110, 40));

        panel_buscar.setBackground(new java.awt.Color(51, 204, 0));
        panel_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_buscarMouseExited(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N

        javax.swing.GroupLayout panel_buscarLayout = new javax.swing.GroupLayout(panel_buscar);
        panel_buscar.setLayout(panel_buscarLayout);
        panel_buscarLayout.setHorizontalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_buscarLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        panel_buscarLayout.setVerticalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 110, -1));

        panel_modificar.setBackground(new java.awt.Color(51, 204, 0));
        panel_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_modificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_modificarMouseExited(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 110, -1));

        panel_mostrar.setBackground(new java.awt.Color(51, 204, 0));
        panel_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseExited(evt);
            }
        });

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("Mostrar");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout panel_mostrarLayout = new javax.swing.GroupLayout(panel_mostrar);
        panel_mostrar.setLayout(panel_mostrarLayout);
        panel_mostrarLayout.setHorizontalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mostrarLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_mostrarLayout.setVerticalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar_cedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_cedulaMousePressed

        if(ingresar_cedula.getText().equals("Ingresar numero de cedula")){
            ingresar_cedula.setText("");
            ingresar_cedula.setForeground(Color.black);
        }

        if(ingresar_apellido. getText().isEmpty()){
            ingresar_apellido.setText("Ingresar apellidos completos");
            ingresar_apellido.setForeground(Color.gray);
        }

        if(ingresar_nombre.getText().isEmpty()){
            ingresar_nombre.setText("Ingresar nombre completo");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_telefono.getText().isEmpty()){
            ingresar_telefono.setText("Ingresar el numero de teléfono");
            ingresar_telefono.setForeground(Color.gray);
        }

        if(ingresar_direccion.getText().isEmpty()){
            ingresar_direccion.setText("Ingresar direccion de residencia");
            ingresar_direccion.setForeground(Color.gray);
        }

        if(ingresar_email.getText().isEmpty()){
            ingresar_email.setText("Ingresar @email");
            ingresar_email.setForeground(Color.gray);
        }

    }//GEN-LAST:event_ingresar_cedulaMousePressed

    private void ingresar_apellidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_apellidoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_apellidoMouseEntered

    private void ingresar_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_apellidoMousePressed

        if(ingresar_cedula.getText().isEmpty()){
            ingresar_cedula.setText("Ingresar numero de cedula");
            ingresar_cedula.setForeground(Color.gray);
        }

        if(ingresar_apellido.getText().equals("Ingresar apellidos completos")){
            ingresar_apellido.setText("");
            ingresar_apellido.setForeground(Color.black);
        }

        if(ingresar_nombre.getText().isEmpty()){
            ingresar_nombre.setText("Ingresar nombre completo");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_telefono.getText().isEmpty()){
            ingresar_telefono.setText("Ingresar el numero de teléfono");
            ingresar_telefono.setForeground(Color.gray);
        }

        if(ingresar_direccion.getText().isEmpty()){
            ingresar_direccion.setText("Ingresar direccion de residencia");
            ingresar_direccion.setForeground(Color.gray);
        }

        if(ingresar_email.getText().isEmpty()){
            ingresar_email.setText("Ingresar @email");
            ingresar_email.setForeground(Color.gray);
        }

    }//GEN-LAST:event_ingresar_apellidoMousePressed

    private void ingresar_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_apellidoActionPerformed

    private void ingresar_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_nombreMousePressed

        if(ingresar_cedula.getText().isEmpty()){
            ingresar_cedula.setText("Ingresar numero de cedula");
            ingresar_cedula.setForeground(Color.gray);
        }

        if(ingresar_apellido.getText().isEmpty()){
            ingresar_apellido.setText("Ingresar apellidos completos");
            ingresar_apellido.setForeground(Color.gray);
        }

        if(ingresar_nombre.getText().equals("Ingresar nombre completo")){
            ingresar_nombre.setText("");
            ingresar_nombre.setForeground(Color.black);
        }

        if(ingresar_telefono.getText().isEmpty()){
            ingresar_telefono.setText("Ingresar el numero de teléfono");
            ingresar_telefono.setForeground(Color.gray);
        }

        if(ingresar_direccion.getText().isEmpty()){
            ingresar_direccion.setText("Ingresar direccion de residencia");
            ingresar_direccion.setForeground(Color.gray);
        }

        if(ingresar_email.getText().isEmpty()){
            ingresar_email.setText("Ingresar @email");
            ingresar_email.setForeground(Color.gray);
        }

    }//GEN-LAST:event_ingresar_nombreMousePressed

    private void ingresar_telefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_telefonoMousePressed

        if(ingresar_cedula.getText().isEmpty()){
            ingresar_cedula.setText("Ingresar numero de cedula");
            ingresar_cedula.setForeground(Color.gray);
        }

        if(ingresar_apellido.getText().isEmpty()){
            ingresar_apellido.setText("Ingresar apellidos completos");
            ingresar_apellido.setForeground(Color.gray);
        }

        if(ingresar_nombre.getText().isEmpty()){
            ingresar_nombre.setText("Ingresar nombre completo");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_telefono.getText().equals("Ingresar el numero de teléfono")){
            ingresar_telefono.setText("");
            ingresar_telefono.setForeground(Color.black);
        }

        if(ingresar_direccion.getText().isEmpty()){
            ingresar_direccion.setText("Ingresar direccion de residencia");
            ingresar_direccion.setForeground(Color.gray);
        }

        if(ingresar_email.getText().isEmpty()){
            ingresar_email.setText("Ingresar @email");
            ingresar_email.setForeground(Color.gray);
        }

    }//GEN-LAST:event_ingresar_telefonoMousePressed

    private void ingresar_direccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_direccionMousePressed

        if(ingresar_cedula.getText().isEmpty()){
            ingresar_cedula.setText("Ingresar numero de cedula");
            ingresar_cedula.setForeground(Color.gray);
        }

        if(ingresar_apellido.getText().isEmpty()){
            ingresar_apellido.setText("Ingresar apellidos completos");
            ingresar_apellido.setForeground(Color.gray);
        }

        if(ingresar_nombre.getText().isEmpty()){
            ingresar_nombre.setText("Ingresar nombre completo");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_telefono.getText().isEmpty()){
            ingresar_telefono.setText("Ingresar el numero de teléfono");
            ingresar_telefono.setForeground(Color.gray);
        }

        if(ingresar_direccion.getText().equals("Ingresar direccion de residencia")){
            ingresar_direccion.setText("");
            ingresar_direccion.setForeground(Color.black);
        }

        if(ingresar_email.getText().isEmpty()){
            ingresar_email.setText("Ingresar @email");
            ingresar_email.setForeground(Color.gray);
        }

    }//GEN-LAST:event_ingresar_direccionMousePressed

    private void ingresar_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_emailMousePressed

        if(ingresar_cedula.getText().isEmpty()){
            ingresar_cedula.setText("Ingresar numero de cedula");
            ingresar_cedula.setForeground(Color.gray);
        }

        if(ingresar_apellido.getText().isEmpty()){
            ingresar_apellido.setText("Ingresar apellidos completos");
            ingresar_apellido.setForeground(Color.gray);
        }

        if(ingresar_nombre.getText().isEmpty()){
            ingresar_nombre.setText("Ingresar nombre completo");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_telefono.getText().isEmpty()){
            ingresar_telefono.setText("Ingresar el numero de teléfono");
            ingresar_telefono.setForeground(Color.gray);
        }

        if(ingresar_direccion.getText().isEmpty()){
            ingresar_direccion.setText("Ingresar direccion de residencia");
            ingresar_direccion.setForeground(Color.gray);
        }

        if(ingresar_email.getText().equals("Ingresar @email")){
            ingresar_email.setText("");
            ingresar_email.setForeground(Color.black);
        }

    }//GEN-LAST:event_ingresar_emailMousePressed

    private void panel_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseEntered
        panel_agregar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_agregarMouseEntered

    private void panel_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseExited
        panel_agregar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_agregarMouseExited

    private void panel_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseEntered
        panel_buscar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_buscarMouseEntered

    private void panel_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseExited
        panel_buscar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_buscarMouseExited

    private void panel_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseEntered
        panel_modificar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_modificarMouseEntered

    private void panel_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseExited
        panel_modificar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_modificarMouseExited

    private void panel_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseEntered
        panel_mostrar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_mostrarMouseEntered

    private void panel_mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseExited
        panel_mostrar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_mostrarMouseExited

    
    
    private void panel_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
             if(ingresar_email.getText().contains("@") && ingresar_email.getText().contains(".")){
                if(ingresar_telefono.getText().length()==10){
                    String query = "INSERT INTO cliente VALUES ("+ Long.parseLong(ingresar_cedula.getText().trim())+",'"+ ingresar_nombre.getText().trim()+"','"+ ingresar_apellido.getText().trim()+"',"+ Long.parseLong(ingresar_telefono.getText().trim())+",'"+ ingresar_email.getText().trim()+"','"+ ingresar_direccion.getText().trim()+"')";
                    JOptionPane.showMessageDialog(this, "Registro exitoso");
                    con.actualizar(query);
                    
                    con.cerrar();
                    ingresar_cedula.setText(null);
                    ingresar_nombre.setText(null);
                    ingresar_apellido.setText(null);
                    ingresar_telefono.setText(null);
                    ingresar_email.setText(null);
                    ingresar_direccion.setText(null);
                    
                }
                }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_agregarMouseClicked

    
    private void panel_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "SELECT * FROM Cliente WHERE cedula_cliente ="+ Long.parseLong(ingresar_cedula.getText().trim());
            ResultSet rs = con.consultar(query);
            
             if (rs.next()){
            
            ingresar_cedula.setText(rs.getString("cedula_cliente"));
            ingresar_nombre.setText(rs.getString("nombre_cliente"));
            ingresar_apellido.setText(rs.getString("apellido_cliente"));
            ingresar_telefono.setText(rs.getString("telefono_cliente"));
            ingresar_email.setText(rs.getString("correo_cliente"));
            ingresar_direccion.setText(rs.getString("direccion_cliente")); 
        }
             else{
            JOptionPane.showMessageDialog(this,"N0 existe el cliente");
        }
            ingresar_cedula.setForeground(Color.BLACK);
            ingresar_nombre.setForeground(Color.BLACK);
            ingresar_apellido.setForeground(Color.BLACK);
            ingresar_telefono.setForeground(Color.BLACK);
            ingresar_email.setForeground(Color.BLACK);
            ingresar_direccion.setForeground(Color.BLACK);
            
            
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_buscarMouseClicked

    
    private void panel_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
             String query = "UPDATE cliente SET nombre_cliente ='" + ingresar_nombre.getText().trim()+"', apellido_cliente ='" + ingresar_apellido.getText().trim()+"', telefono_cliente = "+ Long.parseLong(ingresar_telefono.getText().trim())+", correo_cliente ='"+ ingresar_email.getText().trim()+"', direccion_cliente = '"+ ingresar_direccion.getText().trim()+"' WHERE cedula_cliente = "+ Long.parseLong(ingresar_cedula.getText().trim());
             JOptionPane.showMessageDialog(this,"Datos actualizados");
             con.actualizar(query);
             con.cerrar();
             ingresar_cedula.setText(null);
             ingresar_nombre.setText(null);
             ingresar_apellido.setText(null);
             ingresar_telefono.setText(null);
             ingresar_email.setText(null);
             ingresar_direccion.setText(null);
             
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_panel_modificarMouseClicked
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel email;
    private javax.swing.JLabel icono;
    private javax.swing.JTextField ingresar_apellido;
    private javax.swing.JTextField ingresar_cedula;
    private javax.swing.JTextField ingresar_direccion;
    private javax.swing.JTextField ingresar_email;
    private javax.swing.JTextField ingresar_nombre;
    private javax.swing.JTextField ingresar_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel mostrar;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_agrofacil;
    private javax.swing.JPanel panel_buscar;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_mostrar;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables
}
