/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Antonio
 */
public class Familia extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Familia() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_agrofacil = new javax.swing.JPanel();
        familia = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        id_familia = new javax.swing.JLabel();
        nombre_familia = new javax.swing.JLabel();
        descripcion_familia = new javax.swing.JLabel();
        ingresar_id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ingresar_nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ingresar_descripcion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        panel_agregar = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        icono_agregar = new javax.swing.JLabel();
        panel_buscar = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        icono_buscar = new javax.swing.JLabel();
        panel_modificar = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        icono_modificar = new javax.swing.JLabel();
        panel_mostrar = new javax.swing.JPanel();
        mostrar = new javax.swing.JLabel();
        icono_mostrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agrofacil.setBackground(new java.awt.Color(0, 204, 0));
        panel_agrofacil.setLayout(null);

        familia.setFont(new java.awt.Font("Leelawadee UI", 3, 48)); // NOI18N
        familia.setForeground(new java.awt.Color(255, 255, 255));
        familia.setText("FAMILIA");
        panel_agrofacil.add(familia);
        familia.setBounds(240, 20, 230, 64);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login1.png"))); // NOI18N
        panel_agrofacil.add(icono);
        icono.setBounds(610, 10, 107, 95);

        add(panel_agrofacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 110));

        id_familia.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        id_familia.setText("ID DE FAMILIA");
        add(id_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 30));

        nombre_familia.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombre_familia.setText("NOMBRE DE LA FAMILIA");
        add(nombre_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 230, 30));

        descripcion_familia.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        descripcion_familia.setText("DESCRIPCIÓN DE LA FAMILIA");
        add(descripcion_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        ingresar_id.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_id.setText("Ingrese el ID de la familia");
        ingresar_id.setBorder(null);
        ingresar_id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_idMousePressed(evt);
            }
        });
        add(ingresar_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 260, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 270, -1));

        ingresar_nombre.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_nombre.setText("Ingrese nombre de la familia");
        ingresar_nombre.setBorder(null);
        ingresar_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_nombreMousePressed(evt);
            }
        });
        add(ingresar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 160, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 270, -1));

        ingresar_descripcion.setForeground(new java.awt.Color(153, 153, 153));
        ingresar_descripcion.setText("Ingrese descripcion de la familia");
        ingresar_descripcion.setBorder(null);
        ingresar_descripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar_descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresar_descripcionMousePressed(evt);
            }
        });
        add(ingresar_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 180, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 270, -1));

        panel_agregar.setBackground(new java.awt.Color(51, 204, 0));
        panel_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_agregarMouseExited(evt);
            }
        });

        agregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");

        icono_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregar)
                .addContainerGap())
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 110, 40));

        panel_buscar.setBackground(new java.awt.Color(51, 204, 0));
        panel_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_buscarMouseExited(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");

        icono_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N

        javax.swing.GroupLayout panel_buscarLayout = new javax.swing.GroupLayout(panel_buscar);
        panel_buscar.setLayout(panel_buscarLayout);
        panel_buscarLayout.setHorizontalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_buscarLayout.setVerticalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 410, 110, -1));

        panel_modificar.setBackground(new java.awt.Color(51, 204, 0));
        panel_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_modificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_modificarMouseExited(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");

        icono_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(icono_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar)
                .addContainerGap())
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 410, 120, -1));

        panel_mostrar.setBackground(new java.awt.Color(51, 204, 0));
        panel_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseExited(evt);
            }
        });

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("Mostrar");

        icono_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout panel_mostrarLayout = new javax.swing.GroupLayout(panel_mostrar);
        panel_mostrar.setLayout(panel_mostrarLayout);
        panel_mostrarLayout.setHorizontalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mostrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_mostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrar)
                .addContainerGap())
        );
        panel_mostrarLayout.setVerticalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_idMousePressed

        if(ingresar_id.getText().equals("Ingrese el ID de la familia")){
            ingresar_id.setText("");
            ingresar_id.setForeground(Color.black);
        }

        if(ingresar_nombre. getText().isEmpty()){
            ingresar_nombre.setText("Ingrese nombre de la familia");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_descripcion. getText().isEmpty()){
            ingresar_descripcion.setText("Ingrese descripcion de la familia");
            ingresar_descripcion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingresar_idMousePressed

    private void ingresar_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_nombreMousePressed

        if(ingresar_id. getText().isEmpty()){
            ingresar_id.setText("Ingrese el ID de la familia");
            ingresar_id.setForeground(Color.gray);
        }

        if(ingresar_nombre.getText().equals("Ingrese nombre de la familia")){
            ingresar_nombre.setText("");
            ingresar_nombre.setForeground(Color.black);
        }

        ingresar_descripcion.setText("Ingrese descripcion de la familia");
        ingresar_descripcion.setForeground(Color.gray);

    }//GEN-LAST:event_ingresar_nombreMousePressed

    private void ingresar_descripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_descripcionMousePressed

        if(ingresar_id. getText().isEmpty()){
            ingresar_id.setText("Ingrese el ID de la familia");
            ingresar_id.setForeground(Color.gray);
        }

        if(ingresar_nombre. getText().isEmpty()){
            ingresar_nombre.setText("Ingrese nombre de la familia");
            ingresar_nombre.setForeground(Color.gray);
        }

        if(ingresar_descripcion.getText().equals("Ingrese descripcion de la familia")){
            ingresar_descripcion.setText("");
            ingresar_descripcion.setForeground(Color.black);
        }
    }//GEN-LAST:event_ingresar_descripcionMousePressed

    private void panel_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseEntered
        panel_agregar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_agregarMouseEntered

    private void panel_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseExited
        panel_agregar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_agregarMouseExited

    private void panel_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseEntered
        panel_buscar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_buscarMouseEntered

    private void panel_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseExited
        panel_buscar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_buscarMouseExited

    private void panel_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseEntered
        panel_modificar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_modificarMouseEntered

    private void panel_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseExited
        panel_modificar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_modificarMouseExited

    private void panel_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseEntered
        panel_mostrar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_mostrarMouseEntered

    private void panel_mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseExited
        panel_mostrar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_mostrarMouseExited

    private void panel_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseClicked
        try {
            Conexion con = new Conexion ();
            con.ConexionPostgres();
            
            String query ="INSERT INTO familia VALUES("+ Long.parseLong(ingresar_id.getText().trim())+",'"+ ingresar_nombre.getText().trim()+"','"+ingresar_descripcion.getText().trim()+"')";
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            con.actualizar(query);
            
            con.cerrar();
            ingresar_id.setText(null);
            ingresar_nombre.setText(null);
            ingresar_descripcion.setText(null);
                    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_panel_agregarMouseClicked

    private void panel_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseClicked
       try {
        Conexion con = new Conexion();
        con.ConexionPostgres();
        
        String query ="SELECT * FROM familia WHERE id_familia = "+ Integer.parseInt(ingresar_id.getText().trim());
        
        ResultSet rs = con.consultar(query);
        
        if(rs.next()){
            ingresar_nombre.setText(rs.getString("nombre_familia"));
            ingresar_descripcion.setText(rs.getString("descripcion_familia"));
        }
        else{
            JOptionPane.showMessageDialog(this,"No existe la familia");
        }
        ingresar_id.setForeground(Color.black);
        ingresar_nombre.setForeground(Color.black);
        ingresar_descripcion.setForeground(Color.black);
        
         con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panel_buscarMouseClicked

    private void panel_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query ="UPDATE familia SET nombre_familia = '"+ingresar_nombre.getText().trim()+"', descripcion_familia='"+ingresar_descripcion.getText().trim()+"' where id_familia="+Long.parseLong(ingresar_id.getText().trim());
            JOptionPane.showMessageDialog(this, "Datos actualizados");
            con.actualizar(query);
            
            con.cerrar();
            ingresar_id.setText(null);
            ingresar_descripcion.setText(null);
            ingresar_nombre.setText(null);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_modificarMouseClicked

    // SUBIR   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel descripcion_familia;
    private javax.swing.JLabel familia;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono_agregar;
    private javax.swing.JLabel icono_buscar;
    private javax.swing.JLabel icono_modificar;
    private javax.swing.JLabel icono_mostrar;
    private javax.swing.JLabel id_familia;
    private javax.swing.JTextField ingresar_descripcion;
    private javax.swing.JTextField ingresar_id;
    private javax.swing.JTextField ingresar_nombre;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel mostrar;
    private javax.swing.JLabel nombre_familia;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_agrofacil;
    private javax.swing.JPanel panel_buscar;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_mostrar;
    // End of variables declaration//GEN-END:variables
}
