/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login2
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        fondo_login = new javax.swing.JLabel();
        iniciarsesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        ingreso_usuario = new javax.swing.JTextField();
        raya_usuario = new javax.swing.JSeparator();
        contraseña = new javax.swing.JLabel();
        numeros_contraseña = new javax.swing.JPasswordField();
        raya_contraseña = new javax.swing.JSeparator();
        panel_ingresar = new javax.swing.JPanel();
        ingresar = new javax.swing.JLabel();
        icono_usuario = new javax.swing.JLabel();
        icono_contraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 410, 330));

        fondo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_login.jpg"))); // NOI18N
        jPanel1.add(fondo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 430, 500));

        iniciarsesion.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        iniciarsesion.setText("INICIAR SESIÓN");
        jPanel1.add(iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        usuario.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        usuario.setText("USUARIO");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        ingreso_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ingreso_usuario.setForeground(new java.awt.Color(153, 153, 153));
        ingreso_usuario.setText("Ingrese su nombre de usuario");
        ingreso_usuario.setBorder(null);
        ingreso_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingreso_usuarioMousePressed(evt);
            }
        });
        jPanel1.add(ingreso_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, 30));
        jPanel1.add(raya_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 20));

        contraseña.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        numeros_contraseña.setForeground(new java.awt.Color(153, 153, 153));
        numeros_contraseña.setText("********");
        numeros_contraseña.setBorder(null);
        numeros_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numeros_contraseñaMousePressed(evt);
            }
        });
        jPanel1.add(numeros_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, -1));
        jPanel1.add(raya_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, 10));

        panel_ingresar.setBackground(new java.awt.Color(51, 204, 0));
        panel_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ingresarMouseExited(evt);
            }
        });

        ingresar.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("      INGRESAR");
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_ingresarLayout = new javax.swing.GroupLayout(panel_ingresar);
        panel_ingresar.setLayout(panel_ingresarLayout);
        panel_ingresarLayout.setHorizontalGroup(
            panel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_ingresarLayout.setVerticalGroup(
            panel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panel_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 40));

        icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jPanel1.add(icono_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        icono_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock.png"))); // NOI18N
        jPanel1.add(icono_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingreso_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingreso_usuarioMousePressed
        if(ingreso_usuario.getText().equals("Ingrese su nombre de usuario")){
            ingreso_usuario.setText("");
            ingreso_usuario.setForeground(Color.black);
        }
        if(String.valueOf(numeros_contraseña.getPassword()).isEmpty()){
            numeros_contraseña.setText("********");
            numeros_contraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingreso_usuarioMousePressed

    private void numeros_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeros_contraseñaMousePressed
        if(String.valueOf(numeros_contraseña.getPassword()).equals("********")){
            numeros_contraseña.setText("");
            numeros_contraseña.setForeground(Color.black);
        }

        if(ingreso_usuario.getText().isEmpty()){
            ingreso_usuario.setText("Ingrese su nombre de usuario");
            ingreso_usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_numeros_contraseñaMousePressed

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        try {
            //javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + ingreso_usuario.getText() + "\ncontraseña; " + String.valueOf(numeros_contraseña.getPassword()),"LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            Conexion con = new Conexion ();
            con.ConexionPostgres();

            String query = "SELECT * FROM usuario WHERE usuario = '"+ ingreso_usuario.getText()+"' and contraseña_user = '"+ String.valueOf(numeros_contraseña.getPassword())+"'";

            ResultSet rs = con.consultar(query);

            if(rs.next()){
                principal abrir = new principal();
                abrir.setVisible(true);

                Login.this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "El usuario o constraseña son incorrectos!");
            }
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ingresarMouseClicked

    private void ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseEntered
        ingresar.setBackground(Color.black);
    }//GEN-LAST:event_ingresarMouseEntered

    private void ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseExited
        ingresar.setBackground(Color.green);
    }//GEN-LAST:event_ingresarMouseExited

    private void panel_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ingresarMouseEntered
        panel_ingresar.setBackground(Color.black);
    }//GEN-LAST:event_panel_ingresarMouseEntered

    private void panel_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ingresarMouseExited
        panel_ingresar.setBackground(Color.green);
    }//GEN-LAST:event_panel_ingresarMouseExited

    private void panel_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ingresarMouseClicked
        // TODO add your handling code here:
        try {
            //javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + ingreso_usuario.getText() + "\ncontraseña; " + String.valueOf(numeros_contraseña.getPassword()),"LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            Conexion con = new Conexion ();
            con.ConexionPostgres();

            String query = "SELECT * FROM usuario WHERE usuario = '"+ ingreso_usuario.getText()+"' and contraseña_user = '"+ String.valueOf(numeros_contraseña.getPassword())+"'";

            ResultSet rs = con.consultar(query);

            if(rs.next()){
                principal abrir = new principal();
                abrir.setVisible(true);

                Login.this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "El usuario o constraseña son incorrectos!");
            }
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel fondo_login;
    private javax.swing.JLabel icono_contraseña;
    private javax.swing.JLabel icono_usuario;
    private javax.swing.JLabel ingresar;
    private javax.swing.JTextField ingreso_usuario;
    private javax.swing.JLabel iniciarsesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField numeros_contraseña;
    private javax.swing.JPanel panel_ingresar;
    private javax.swing.JSeparator raya_contraseña;
    private javax.swing.JSeparator raya_usuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
