/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Antonio
 */
public class Producto extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Producto() {
        try {
            initComponents();
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "select * from familia order by id_familia";
            
            ResultSet rs=con.consultar(query);
            
            while(rs.next())
            {
                familia_pertenece.addItem(rs.getLong("id_familia")+ "-" +rs.getString("nombre_familia"));
            }
            
            con.cerrar();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panel_agrofacil = new javax.swing.JPanel();
        producto = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        id_producto = new javax.swing.JLabel();
        nombre_producto = new javax.swing.JLabel();
        descrpcion_producto = new javax.swing.JLabel();
        valor_producto = new javax.swing.JLabel();
        familia = new javax.swing.JLabel();
        proveedor_producto = new javax.swing.JLabel();
        ingrese_idproducto = new javax.swing.JTextField();
        ingrese_nombre = new javax.swing.JTextField();
        ingrese_descripcion = new javax.swing.JTextField();
        ingrese_valor = new javax.swing.JTextField();
        ingrese_proveedor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        panel_modificar = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        icono_modificar = new javax.swing.JLabel();
        panel_mostrar = new javax.swing.JPanel();
        mostrar = new javax.swing.JLabel();
        icono_mostrar = new javax.swing.JLabel();
        panel_buscar = new javax.swing.JPanel();
        icono_buscar = new javax.swing.JLabel();
        buscar = new javax.swing.JLabel();
        panel_agregar = new javax.swing.JPanel();
        icono_agregrar = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        familia_pertenece = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JLabel();
        ingrese_cantidad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        stock_minimo = new javax.swing.JLabel();
        ingrese_stock = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agrofacil.setBackground(new java.awt.Color(0, 204, 0));
        panel_agrofacil.setLayout(null);

        producto.setFont(new java.awt.Font("Leelawadee UI", 3, 48)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setText("PRODUCTO");
        panel_agrofacil.add(producto);
        producto.setBounds(220, 20, 280, 64);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login1.png"))); // NOI18N
        panel_agrofacil.add(icono);
        icono.setBounds(610, 10, 107, 95);

        bg.add(panel_agrofacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 110));

        id_producto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        id_producto.setText("ID DEL PRODUCTO");
        bg.add(id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 40));

        nombre_producto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombre_producto.setText("NOMBRE DEL PRODUCTO");
        bg.add(nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 40));

        descrpcion_producto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        descrpcion_producto.setText("DESCRIPCION DEL PRODUCTO");
        bg.add(descrpcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 40));

        valor_producto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        valor_producto.setText("VALOR DEL PRODUCTO");
        bg.add(valor_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 40));

        familia.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        familia.setText("FAMILIA LA CUAL PERTENECE");
        bg.add(familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 40));

        proveedor_producto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        proveedor_producto.setText("PROVEEDOR DEL PRODUCTO");
        bg.add(proveedor_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 40));

        ingrese_idproducto.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_idproducto.setText("Ingrese el ID del producto");
        ingrese_idproducto.setBorder(null);
        ingrese_idproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_idproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_idproductoMousePressed(evt);
            }
        });
        bg.add(ingrese_idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        ingrese_nombre.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_nombre.setText("Ingrese el nombre del producto");
        ingrese_nombre.setBorder(null);
        ingrese_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_nombreMousePressed(evt);
            }
        });
        bg.add(ingrese_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 30));

        ingrese_descripcion.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_descripcion.setText("Ingrese la descripcion del producto");
        ingrese_descripcion.setBorder(null);
        ingrese_descripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_descripcionMousePressed(evt);
            }
        });
        bg.add(ingrese_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        ingrese_valor.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_valor.setText("Ingrese el valor del producto");
        ingrese_valor.setBorder(null);
        ingrese_valor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_valor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_valorMousePressed(evt);
            }
        });
        bg.add(ingrese_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 30));

        ingrese_proveedor.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_proveedor.setText("Ingrese el proveedor del producto");
        ingrese_proveedor.setBorder(null);
        ingrese_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_proveedorMousePressed(evt);
            }
        });
        bg.add(ingrese_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, 30));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 260, 10));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 260, 10));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 10));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 260, 10));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 260, 10));

        panel_modificar.setBackground(new java.awt.Color(51, 204, 0));
        panel_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_modificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_modificarMouseExited(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(panel_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        panel_mostrar.setBackground(new java.awt.Color(51, 204, 0));
        panel_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseExited(evt);
            }
        });

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("Mostrar");
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout panel_mostrarLayout = new javax.swing.GroupLayout(panel_mostrar);
        panel_mostrar.setLayout(panel_mostrarLayout);
        panel_mostrarLayout.setHorizontalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mostrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrar)
                .addContainerGap())
        );
        panel_mostrarLayout.setVerticalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(panel_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 100, -1));

        panel_buscar.setBackground(new java.awt.Color(51, 204, 0));
        panel_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_buscarMouseExited(evt);
            }
        });

        icono_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N

        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_buscarLayout = new javax.swing.GroupLayout(panel_buscar);
        panel_buscar.setLayout(panel_buscarLayout);
        panel_buscarLayout.setHorizontalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar)
                .addContainerGap())
        );
        panel_buscarLayout.setVerticalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_buscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, 40));

        panel_agregar.setBackground(new java.awt.Color(51, 204, 0));
        panel_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_agregarMouseExited(evt);
            }
        });

        icono_agregrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N

        agregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_agregrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icono_agregrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, 40));

        familia_pertenece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        bg.add(familia_pertenece, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 250, 30));

        cantidad.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cantidad.setText("CANTIDAD DEL PRODUTO");
        bg.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        ingrese_cantidad.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_cantidad.setText("Ingrese la cantidad del producto");
        ingrese_cantidad.setBorder(null);
        ingrese_cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_cantidadMousePressed(evt);
            }
        });
        bg.add(ingrese_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 30));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 10));

        stock_minimo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        stock_minimo.setText("STOCK MINIMO");
        bg.add(stock_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, 30));

        ingrese_stock.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_stock.setText("Ingrese el stock minimo");
        ingrese_stock.setBorder(null);
        ingrese_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_stockMousePressed(evt);
            }
        });
        bg.add(ingrese_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, 30));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 260, 10));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void ingrese_idproductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_idproductoMousePressed
        if(ingrese_idproducto.getText().equals("Ingrese el ID del producto")){
            ingrese_idproducto.setText("");
            ingrese_idproducto.setForeground(Color.black);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre del producto");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_descripcion. getText().isEmpty()){
            ingrese_descripcion.setText("Ingrese la descripcion del producto");
            ingrese_descripcion.setForeground(Color.gray);
        }

        if(ingrese_valor. getText().isEmpty()){
            ingrese_valor.setText("Ingrese el valor del producto");
            ingrese_valor.setForeground(Color.gray);
        }


        if(ingrese_proveedor. getText().isEmpty()){
            ingrese_proveedor.setText("Ingrese el proveedor del producto");
            ingrese_proveedor.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);   
        }
        
        if(ingrese_stock.getText().isEmpty()){
            ingrese_stock.setText("Ingrese el stock minimo");
            ingrese_stock.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_ingrese_idproductoMousePressed

    private void ingrese_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_nombreMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_nombre.getText().equals("Ingrese el nombre del producto")){
            ingrese_nombre.setText("");
            ingrese_nombre.setForeground(Color.black);
        }

        if(ingrese_descripcion. getText().isEmpty()){
            ingrese_descripcion.setText("Ingrese la descripcion del producto");
            ingrese_descripcion.setForeground(Color.gray);
        }

        if(ingrese_valor. getText().isEmpty()){
            ingrese_valor.setText("Ingrese el valor del producto");
            ingrese_valor.setForeground(Color.gray);
        }

        if(ingrese_proveedor. getText().isEmpty()){
            ingrese_proveedor.setText("Ingrese el proveedor del producto");
            ingrese_proveedor.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);   
        }
        
        if(ingrese_stock.getText().isEmpty()){
            ingrese_stock.setText("Ingrese el stock minimo");
            ingrese_stock.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_ingrese_nombreMousePressed

    private void ingrese_descripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_descripcionMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre del producto");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_descripcion.getText().equals("Ingrese la descripcion del producto")){
            ingrese_descripcion.setText("");
            ingrese_descripcion.setForeground(Color.black);
        }

        if(ingrese_valor. getText().isEmpty()){
            ingrese_valor.setText("Ingrese el valor del producto");
            ingrese_valor.setForeground(Color.gray);
        }

        if(ingrese_proveedor. getText().isEmpty()){
            ingrese_proveedor.setText("Ingrese el proveedor del producto");
            ingrese_proveedor.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);   
        }
        
        if(ingrese_stock.getText().isEmpty()){
            ingrese_stock.setText("Ingrese el stock minimo");
            ingrese_stock.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_ingrese_descripcionMousePressed

    private void ingrese_valorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_valorMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre del producto");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_descripcion. getText().isEmpty()){
            ingrese_descripcion.setText("Ingrese la descripcion del producto");
            ingrese_descripcion.setForeground(Color.gray);
        }

        if(ingrese_valor.getText().equals("Ingrese el valor del producto")){
            ingrese_valor.setText("");
            ingrese_valor.setForeground(Color.black);
        }

        if(ingrese_proveedor. getText().isEmpty()){
            ingrese_proveedor.setText("Ingrese el proveedor del producto");
            ingrese_proveedor.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);   
        }
        
        if(ingrese_stock.getText().isEmpty()){
            ingrese_stock.setText("Ingrese el stock minimo");
            ingrese_stock.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_ingrese_valorMousePressed

    private void ingrese_proveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_proveedorMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre del producto");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_descripcion. getText().isEmpty()){
            ingrese_descripcion.setText("Ingrese la descripcion del producto");
            ingrese_descripcion.setForeground(Color.gray);
        }

        if(ingrese_valor. getText().isEmpty()){
            ingrese_valor.setText("Ingrese el valor del producto");
            ingrese_valor.setForeground(Color.gray);
        }

        if(ingrese_proveedor.getText().equals("Ingrese el proveedor del producto")){
            ingrese_proveedor.setText("");
            ingrese_proveedor.setForeground(Color.black);
        }
        
        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);   
        }
        
        if(ingrese_stock.getText().isEmpty()){
            ingrese_stock.setText("Ingrese el stock minimo");
            ingrese_stock.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_ingrese_proveedorMousePressed

    private void panel_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseEntered
        panel_agregar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_agregarMouseEntered

    private void panel_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseExited
        panel_agregar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_agregarMouseExited

    private void panel_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseEntered
        panel_buscar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_buscarMouseEntered

    private void panel_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseExited
        panel_buscar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_buscarMouseExited

    private void panel_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseEntered
        panel_modificar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_modificarMouseEntered

    private void panel_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseExited
        panel_modificar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_modificarMouseExited

    private void panel_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseEntered
        panel_mostrar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_mostrarMouseEntered

    private void panel_mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseExited
        panel_mostrar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_mostrarMouseExited

    
    private void ingrese_cantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_cantidadMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre del producto");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_descripcion. getText().isEmpty()){
            ingrese_descripcion.setText("Ingrese la descripcion del producto");
            ingrese_descripcion.setForeground(Color.gray);
        }

        if(ingrese_valor. getText().isEmpty()){
            ingrese_valor.setText("Ingrese el valor del producto");
            ingrese_valor.setForeground(Color.gray);
        }

        if(ingrese_proveedor. getText().isEmpty()){
            ingrese_proveedor.setText("Ingrese el proveedor del producto");
            ingrese_proveedor.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().equals("Ingrese la cantidad del producto")){
            ingrese_cantidad.setText("");
            ingrese_cantidad.setForeground(Color.black);   
        }
        
        if(ingrese_stock.getText().isEmpty()){
            ingrese_stock.setText("Ingrese el stock minimo");
            ingrese_stock.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_ingrese_cantidadMousePressed

    
    
    private void panel_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseClicked
        try {
            String item1 = (String) familia_pertenece.getSelectedItem();
            java.util.StringTokenizer st = new java.util.StringTokenizer(item1,"-");
            String id_f = st.nextToken();
            
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query ="INSERT INTO producto VALUES("+Long.parseLong(ingrese_idproducto.getText().trim())+",'"+ingrese_nombre.getText().trim()+"','"+ingrese_descripcion.getText().trim()+"',"+Long.parseLong(id_f)+","+Long.parseLong(ingrese_proveedor.getText().trim())+","+Long.parseLong(ingrese_cantidad.getText().trim())+","+Long.parseLong(ingrese_stock.getText().trim())+","+Double.parseDouble(ingrese_valor.getText().trim())+")";
            JOptionPane.showMessageDialog(this,"Registro exitoso");
            con.actualizar(query);
            
            con.cerrar();
            nombre_producto.setText(null);
            id_producto.setText(null);
            descrpcion_producto.setText(null);
            ingrese_stock.setText(null);
            ingrese_cantidad.setText(null);
            valor_producto.setText(null);
            ingrese_proveedor.setText(null);
            familia_pertenece.setSelectedItem("Seleccione");        
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_agregarMouseClicked

    
    
    private void ingrese_stockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_stockMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre del producto");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_descripcion. getText().isEmpty()){
            ingrese_descripcion.setText("Ingrese la descripcion del producto");
            ingrese_descripcion.setForeground(Color.gray);
        }

        if(ingrese_valor. getText().isEmpty()){
            ingrese_valor.setText("Ingrese el valor del producto");
            ingrese_valor.setForeground(Color.gray);
        }

        if(ingrese_proveedor. getText().isEmpty()){
            ingrese_proveedor.setText("Ingrese el proveedor del producto");
            ingrese_proveedor.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);   
        }
        
        if(ingrese_stock.getText().equals("Ingrese el stock minimo")){
            ingrese_stock.setText("");
            ingrese_stock.setForeground(Color.black);   
        }
    }//GEN-LAST:event_ingrese_stockMousePressed

    private void panel_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
           String query ="SELECT * FROM producto WHERE id_producto = "+ Long.parseLong(ingrese_idproducto.getText().trim());
           
           ResultSet rs =con.consultar(query);
           
           if(rs.next()){
              ingrese_nombre.setText(rs.getString("nombre_producto"));
              ingrese_descripcion.setText(rs.getString("descripcion_producto"));
              ingrese_stock.setText(rs.getString("stock_minimo_producto"));
              ingrese_cantidad.setText(rs.getString("existencia_producto"));
              ingrese_valor.setText(rs.getString("valor_producto"));
              ingrese_proveedor.setText(rs.getString("nit_provedor"));
           }
           else{
               JOptionPane.showMessageDialog(this, "No existe el producto");
           }
            ingrese_idproducto.setForeground(Color.black);
            ingrese_valor.setForeground(Color.black);
            ingrese_descripcion.setForeground(Color.black);
            ingrese_stock.setForeground(Color.black);
            ingrese_nombre.setForeground(Color.black);
            ingrese_cantidad.setForeground(Color.black);
            ingrese_proveedor.setForeground(Color.BLACK);
            
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_buscarMouseClicked

    private void panel_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseClicked
       try{
        String item1 = (String) familia_pertenece.getSelectedItem();
        java.util.StringTokenizer st = new java.util.StringTokenizer(item1, "-");
        String id_f= st.nextToken();
        
        Conexion con = new Conexion();
        con.ConexionPostgres();
        
        String query ="update producto set nombre_producto = '"+ nombre_producto.getText().trim()+"', descripcion_producto='"+ingrese_descripcion.getText().trim()+"', id_familia="+ Long.parseLong(id_f) +", nit_proveedor="+ Long.parseLong(ingrese_proveedor.getText().trim()) +", stock_minimo_producto="+Long.parseLong(ingrese_stock.getText().trim())+",existencia_producto="+Long.parseLong(ingrese_cantidad.getText().trim())+", valor_producto="+Long.parseLong(ingrese_valor.getText().trim())+" where id_producto="+Long.parseLong(ingrese_idproducto.getText().trim());
        JOptionPane.showMessageDialog(this,"Datos actualizados");
        con.actualizar(query);
        
        con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panel_modificarMouseClicked

    // SUBIR   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel descrpcion_producto;
    private javax.swing.JLabel familia;
    private javax.swing.JComboBox<String> familia_pertenece;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono_agregrar;
    private javax.swing.JLabel icono_buscar;
    private javax.swing.JLabel icono_modificar;
    private javax.swing.JLabel icono_mostrar;
    private javax.swing.JLabel id_producto;
    private javax.swing.JTextField ingrese_cantidad;
    private javax.swing.JTextField ingrese_descripcion;
    private javax.swing.JTextField ingrese_idproducto;
    private javax.swing.JTextField ingrese_nombre;
    private javax.swing.JTextField ingrese_proveedor;
    private javax.swing.JTextField ingrese_stock;
    private javax.swing.JTextField ingrese_valor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel mostrar;
    private javax.swing.JLabel nombre_producto;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_agrofacil;
    private javax.swing.JPanel panel_buscar;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_mostrar;
    private javax.swing.JLabel producto;
    private javax.swing.JLabel proveedor_producto;
    private javax.swing.JLabel stock_minimo;
    private javax.swing.JLabel valor_producto;
    // End of variables declaration//GEN-END:variables
}
