/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Antonio
 */
public class Proveedor extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Proveedor() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_agrofacil = new javax.swing.JPanel();
        proveedor = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        nit = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        ingrese_nit = new javax.swing.JTextField();
        ingrese_nombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ingrese_telefono = new javax.swing.JTextField();
        ingrese_direccion = new javax.swing.JTextField();
        ingrese_contacto = new javax.swing.JTextField();
        ingrese_email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        panel_agregar = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        icono_agregar = new javax.swing.JLabel();
        panel_buscar = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        icono_buscar = new javax.swing.JLabel();
        panel_modificar = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        icono_modificar = new javax.swing.JLabel();
        panel_mostrar = new javax.swing.JPanel();
        mostrar = new javax.swing.JLabel();
        icono_mostrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agrofacil.setBackground(new java.awt.Color(0, 204, 0));
        panel_agrofacil.setLayout(null);

        proveedor.setFont(new java.awt.Font("Leelawadee UI", 3, 48)); // NOI18N
        proveedor.setForeground(new java.awt.Color(255, 255, 255));
        proveedor.setText("PROVEEDOR");
        panel_agrofacil.add(proveedor);
        proveedor.setBounds(190, 20, 300, 64);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login1.png"))); // NOI18N
        panel_agrofacil.add(icono);
        icono.setBounds(610, 10, 107, 95);

        add(panel_agrofacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 110));

        nit.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nit.setText("NIT DE PROVEEDOR");
        add(nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        nombre.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombre.setText("NOMBRE DE PROVEEDOR");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 30));

        direccion.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        direccion.setText("DIRECCION DE PROVEEDOR");
        add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, 30));

        email.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        email.setText("E-MAIL DEL PROVEEDOR");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, 30));

        telefono.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        telefono.setText("TELEFONO DE PROVEEDOR");
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        contacto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        contacto.setText("CONTACTO DE PROVEEDOR");
        add(contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 30));

        ingrese_nit.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_nit.setText("Ingrese el NIT");
        ingrese_nit.setBorder(null);
        ingrese_nit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_nit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_nitMousePressed(evt);
            }
        });
        add(ingrese_nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, 30));

        ingrese_nombre.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_nombre.setText("Ingrese el nombre");
        ingrese_nombre.setBorder(null);
        ingrese_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_nombreMousePressed(evt);
            }
        });
        add(ingrese_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 220, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 280, 10));

        ingrese_telefono.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_telefono.setText("Ingrese el numero de telefono");
        ingrese_telefono.setBorder(null);
        ingrese_telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_telefonoMousePressed(evt);
            }
        });
        add(ingrese_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 30));

        ingrese_direccion.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_direccion.setText("Ingrese direccion de residencia");
        ingrese_direccion.setBorder(null);
        ingrese_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_direccionMousePressed(evt);
            }
        });
        add(ingrese_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, 30));

        ingrese_contacto.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_contacto.setText("Ingrese numero de contacto");
        ingrese_contacto.setBorder(null);
        ingrese_contacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_contacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_contactoMousePressed(evt);
            }
        });
        add(ingrese_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 250, 30));

        ingrese_email.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_email.setText("Ingrese el @email");
        ingrese_email.setBorder(null);
        ingrese_email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingrese_emailMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_emailMousePressed(evt);
            }
        });
        add(ingrese_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 260, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 260, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 280, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 280, 10));

        panel_agregar.setBackground(new java.awt.Color(51, 204, 0));
        panel_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_agregarMouseExited(evt);
            }
        });

        agregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 400, 110, 40));

        panel_buscar.setBackground(new java.awt.Color(51, 204, 0));
        panel_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_buscarMouseExited(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N

        javax.swing.GroupLayout panel_buscarLayout = new javax.swing.GroupLayout(panel_buscar);
        panel_buscar.setLayout(panel_buscarLayout);
        panel_buscarLayout.setHorizontalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar)
                .addContainerGap())
        );
        panel_buscarLayout.setVerticalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, 40));

        panel_modificar.setBackground(new java.awt.Color(51, 204, 0));
        panel_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_modificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_modificarMouseExited(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 400, 110, 40));

        panel_mostrar.setBackground(new java.awt.Color(51, 204, 0));
        panel_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseExited(evt);
            }
        });

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("Mostrar");
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout panel_mostrarLayout = new javax.swing.GroupLayout(panel_mostrar);
        panel_mostrar.setLayout(panel_mostrarLayout);
        panel_mostrarLayout.setHorizontalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mostrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_mostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrar)
                .addContainerGap())
        );
        panel_mostrarLayout.setVerticalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 400, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed

    }//GEN-LAST:event_emailMousePressed

    private void ingrese_nitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_nitMousePressed

        if(ingrese_nit.getText().equals("Ingrese el NIT")){
            ingrese_nit.setText("");
            ingrese_nit.setForeground(Color.black);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_telefono. getText().isEmpty()){
            ingrese_telefono.setText("Ingrese el numero de telefono");
            ingrese_telefono.setForeground(Color.gray);
        }

        if(ingrese_direccion. getText().isEmpty()){
            ingrese_direccion.setText("Ingrese direccion de residencia");
            ingrese_direccion.setForeground(Color.gray);
        }

        if(ingrese_contacto. getText().isEmpty()){
            ingrese_contacto.setText("Ingrese numero de contacto");
            ingrese_contacto.setForeground(Color.gray);
        }

        if(ingrese_email. getText().isEmpty()){
            ingrese_email.setText("Ingrese el @email");
            ingrese_email.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_nitMousePressed

    private void ingrese_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_nombreMousePressed

        if(ingrese_nit. getText().isEmpty()){
            ingrese_nit.setText("Ingrese el NIT");
            ingrese_nit.setForeground(Color.gray);
        }

        if(ingrese_nombre.getText().equals("Ingrese el nombre")){
            ingrese_nombre.setText("");
            ingrese_nombre.setForeground(Color.black);
        }

        if(ingrese_telefono. getText().isEmpty()){
            ingrese_telefono.setText("Ingrese el numero de telefono");
            ingrese_telefono.setForeground(Color.gray);
        }

        if(ingrese_direccion. getText().isEmpty()){
            ingrese_direccion.setText("Ingrese direccion de residencia");
            ingrese_direccion.setForeground(Color.gray);
        }

        if(ingrese_contacto. getText().isEmpty()){
            ingrese_contacto.setText("Ingrese numero de contacto");
            ingrese_contacto.setForeground(Color.gray);
        }

        if(ingrese_email. getText().isEmpty()){
            ingrese_email.setText("Ingrese el @email");
            ingrese_email.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_nombreMousePressed

    private void ingrese_telefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_telefonoMousePressed
        if(ingrese_nit. getText().isEmpty()){
            ingrese_nit.setText("Ingrese el NIT");
            ingrese_nit.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_telefono.getText().equals("Ingrese el numero de telefono")){
            ingrese_telefono.setText("");
            ingrese_telefono.setForeground(Color.black);
        }

        if(ingrese_direccion. getText().isEmpty()){
            ingrese_direccion.setText("Ingrese direccion de residencia");
            ingrese_direccion.setForeground(Color.gray);
        }

        if(ingrese_contacto. getText().isEmpty()){
            ingrese_contacto.setText("Ingrese numero de contacto");
            ingrese_contacto.setForeground(Color.gray);
        }

        if(ingrese_email. getText().isEmpty()){
            ingrese_email.setText("Ingrese el @email");
            ingrese_email.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_telefonoMousePressed

    private void ingrese_direccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_direccionMousePressed

        if(ingrese_nit. getText().isEmpty()){
            ingrese_nit.setText("Ingrese el NIT");
            ingrese_nit.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_telefono. getText().isEmpty()){
            ingrese_telefono.setText("Ingrese el numero de telefono");
            ingrese_telefono.setForeground(Color.gray);
        }

        if(ingrese_direccion.getText().equals("Ingrese direccion de residencia")){
            ingrese_direccion.setText("");
            ingrese_direccion.setForeground(Color.black);
        }

        if(ingrese_contacto. getText().isEmpty()){
            ingrese_contacto.setText("Ingrese numero de contacto");
            ingrese_contacto.setForeground(Color.gray);
        }

        if(ingrese_email. getText().isEmpty()){
            ingrese_email.setText("Ingrese el @email");
            ingrese_email.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_direccionMousePressed

    private void ingrese_contactoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_contactoMousePressed

        if(ingrese_nit. getText().isEmpty()){
            ingrese_nit.setText("Ingrese el NIT");
            ingrese_nit.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_telefono. getText().isEmpty()){
            ingrese_telefono.setText("Ingrese el numero de telefono");
            ingrese_telefono.setForeground(Color.gray);
        }

        if(ingrese_direccion. getText().isEmpty()){
            ingrese_direccion.setText("Ingrese direccion de residencia");
            ingrese_direccion.setForeground(Color.gray);
        }

        if(ingrese_contacto.getText().equals("Ingrese numero de contacto")){
            ingrese_contacto.setText("");
            ingrese_contacto.setForeground(Color.black);
        }

        if(ingrese_email. getText().isEmpty()){
            ingrese_email.setText("Ingrese el @email");
            ingrese_email.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_contactoMousePressed

    private void ingrese_emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_emailMouseEntered

    }//GEN-LAST:event_ingrese_emailMouseEntered

    private void ingrese_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_emailMousePressed

        if(ingrese_nit. getText().isEmpty()){
            ingrese_nit.setText("Ingrese el NIT");
            ingrese_nit.setForeground(Color.gray);
        }

        if(ingrese_nombre. getText().isEmpty()){
            ingrese_nombre.setText("Ingrese el nombre");
            ingrese_nombre.setForeground(Color.gray);
        }

        if(ingrese_telefono. getText().isEmpty()){
            ingrese_telefono.setText("Ingrese el numero de telefono");
            ingrese_telefono.setForeground(Color.gray);
        }

        if(ingrese_direccion. getText().isEmpty()){
            ingrese_direccion.setText("Ingrese direccion de residencia");
            ingrese_direccion.setForeground(Color.gray);
        }

        if(ingrese_contacto. getText().isEmpty()){
            ingrese_contacto.setText("Ingrese numero de contacto");
            ingrese_contacto.setForeground(Color.gray);
        }

        if(ingrese_email.getText().equals("Ingrese el @email")){
            ingrese_email.setText("");
            ingrese_email.setForeground(Color.black);
        }
    }//GEN-LAST:event_ingrese_emailMousePressed

    private void panel_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseEntered
        panel_agregar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_agregarMouseEntered

    private void panel_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseExited
        panel_agregar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_agregarMouseExited

    private void panel_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseEntered
        panel_buscar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_buscarMouseEntered

    private void panel_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseExited
        panel_buscar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_buscarMouseExited

    private void panel_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseEntered
        panel_modificar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_modificarMouseEntered

    private void panel_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseExited
        panel_modificar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_modificarMouseExited

    private void panel_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseEntered
        panel_mostrar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_mostrarMouseEntered

    private void panel_mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseExited
        panel_mostrar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_mostrarMouseExited

    private void panel_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
             if(ingrese_email.getText().contains("@") && ingrese_email.getText().contains(".")){
                if(ingrese_telefono.getText().length()==10 && ingrese_contacto.getText().length()==10){
                  String query = "INSERT INTO proveedor VALUES ("+ Long.parseLong(ingrese_nit.getText().trim())+",'"+ ingrese_nombre.getText().trim()+"','"+ ingrese_email.getText().trim()+"',"+ Long.parseLong(ingrese_telefono.getText().trim())+",'"+ ingrese_direccion.getText().trim()+"',"+ Long.parseLong(ingrese_contacto.getText().trim())+")";  
                  JOptionPane.showMessageDialog(this,"Registro exitoso");
                  con.consultar(query);
                  con.cerrar();
                  ingrese_nit.setText(null);
                  ingrese_nombre.setText(null);
                  ingrese_email.setText(null);
                  ingrese_telefono.setText(null);
                  ingrese_direccion.setText(null);
                  ingrese_contacto.setText(null);
                }
             }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_agregarMouseClicked

    private void panel_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
             String query = "SELECT * FROM proveedor WHERE nit_proveedor ="+ Long.parseLong(ingrese_nit.getText().trim());
             ResultSet rs = con.consultar(query);
             
             if (rs.next()){
            
            ingrese_nit.setText(rs.getString("nit_proveedor"));
            ingrese_nombre.setText(rs.getString("nombre_proveedor"));
             ingrese_email.setText(rs.getString("correo_proveedor"));
            ingrese_telefono.setText(rs.getString("telefono_proveedor"));
            ingrese_direccion.setText(rs.getString("direccion_proveedor")); 
            ingrese_contacto.setText(rs.getString("contacto_proveedor")); 
        }
             
             else{
            JOptionPane.showMessageDialog(this,"N0 existe el proveedor");
        }
            ingrese_nit.setForeground(Color.BLACK);
            ingrese_nombre.setForeground(Color.BLACK);
            ingrese_email.setForeground(Color.BLACK);
            ingrese_telefono.setForeground(Color.BLACK);
            ingrese_direccion.setForeground(Color.BLACK);
            ingrese_contacto.setForeground(Color.BLACK);
            
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_buscarMouseClicked

    private void panel_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseClicked
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
             String query = "UPDATE proveedor SET nombre_proveedor ='" + ingrese_nombre.getText().trim()+"', correo_proveedor ='"+ ingrese_email.getText().trim()+"', telefono_proveedor = "+ Long.parseLong(ingrese_telefono.getText().trim())+", direccion_proveedor = '"+ ingrese_direccion.getText().trim()+"',contacto_proveedor = "+ Long.parseLong(ingrese_contacto.getText().trim())+" WHERE nit_proveedor = "+ Long.parseLong(ingrese_nit.getText().trim());
             JOptionPane.showMessageDialog(this, "Datos actualizados");
             con.actualizar(query);
             con.cerrar();
             ingrese_nit.setText(null);
             ingrese_nombre.setText(null);
             ingrese_email.setText(null);
             ingrese_telefono.setText(null);
             ingrese_direccion.setText(null);
             ingrese_contacto.setText(null);
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panel_modificarMouseClicked

    // SUBIR   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel email;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono_agregar;
    private javax.swing.JLabel icono_buscar;
    private javax.swing.JLabel icono_modificar;
    private javax.swing.JLabel icono_mostrar;
    private javax.swing.JTextField ingrese_contacto;
    private javax.swing.JTextField ingrese_direccion;
    private javax.swing.JTextField ingrese_email;
    private javax.swing.JTextField ingrese_nit;
    private javax.swing.JTextField ingrese_nombre;
    private javax.swing.JTextField ingrese_telefono;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel mostrar;
    private javax.swing.JLabel nit;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_agrofacil;
    private javax.swing.JPanel panel_buscar;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_mostrar;
    private javax.swing.JLabel proveedor;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables
}
