/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Antonio
 */
public class Venta_detalle extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Venta_detalle() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_agrofacil = new javax.swing.JPanel();
        venta = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        detalle = new javax.swing.JLabel();
        id_venta = new javax.swing.JLabel();
        id_producto = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        ingrese_idproducto = new javax.swing.JTextField();
        ingrese_idventa = new javax.swing.JTextField();
        ingrese_subtotal = new javax.swing.JTextField();
        ingrese_detalle = new javax.swing.JTextField();
        ingrese_cantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        panel_agregar = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        icono_agregar = new javax.swing.JLabel();
        panel_buscar = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        icono_buscar = new javax.swing.JLabel();
        panel_modificar = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        icono_modificar = new javax.swing.JLabel();
        panel_mostrar = new javax.swing.JPanel();
        mostrar = new javax.swing.JLabel();
        icono_mostrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agrofacil.setBackground(new java.awt.Color(0, 204, 0));
        panel_agrofacil.setLayout(null);

        venta.setFont(new java.awt.Font("Leelawadee UI", 3, 48)); // NOI18N
        venta.setForeground(new java.awt.Color(255, 255, 255));
        venta.setText("DETALLES VENTAS");
        panel_agrofacil.add(venta);
        venta.setBounds(100, 20, 450, 64);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login1.png"))); // NOI18N
        panel_agrofacil.add(icono);
        icono.setBounds(610, 10, 107, 95);

        add(panel_agrofacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 110));

        detalle.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        detalle.setText("DETALLE DE VENTA");
        add(detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 40));

        id_venta.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        id_venta.setText("ID DE VENTA");
        add(id_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 40));

        id_producto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        id_producto.setText("ID DE PRODUCTO");
        add(id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 40));

        cantidad.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cantidad.setText("CANTIDAD DE PRODUCTO");
        add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        subtotal.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        subtotal.setText("SUBTOTAL DEL DETALLE");
        add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 40));

        ingrese_idproducto.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_idproducto.setText("Ingrese el ID del producto");
        ingrese_idproducto.setBorder(null);
        ingrese_idproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_idproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_idproductoMousePressed(evt);
            }
        });
        add(ingrese_idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, 30));

        ingrese_idventa.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_idventa.setText("Ingrese el ID de la venta");
        ingrese_idventa.setBorder(null);
        ingrese_idventa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_idventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_idventaMousePressed(evt);
            }
        });
        add(ingrese_idventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 250, 30));

        ingrese_subtotal.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_subtotal.setText("Ingrese el subtotal del detalle");
        ingrese_subtotal.setBorder(null);
        ingrese_subtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_subtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_subtotalMousePressed(evt);
            }
        });
        add(ingrese_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 250, 30));

        ingrese_detalle.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_detalle.setText("Ingrese el detalle de venta");
        ingrese_detalle.setBorder(null);
        ingrese_detalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_detalleMousePressed(evt);
            }
        });
        add(ingrese_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 260, 30));

        ingrese_cantidad.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_cantidad.setText("Ingrese la cantidad del producto");
        ingrese_cantidad.setBorder(null);
        ingrese_cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrese_cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_cantidadMousePressed(evt);
            }
        });
        ingrese_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingrese_cantidadActionPerformed(evt);
            }
        });
        add(ingrese_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 290, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 240, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 240, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 240, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 240, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 260, -1));

        panel_agregar.setBackground(new java.awt.Color(51, 204, 0));
        panel_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_agregarMouseExited(evt);
            }
        });

        agregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icono_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar)
                .addContainerGap())
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 110, 40));

        panel_buscar.setBackground(new java.awt.Color(51, 204, 0));
        panel_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_buscarMouseExited(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N

        javax.swing.GroupLayout panel_buscarLayout = new javax.swing.GroupLayout(panel_buscar);
        panel_buscar.setLayout(panel_buscarLayout);
        panel_buscarLayout.setHorizontalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_buscarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(icono_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_buscarLayout.setVerticalGroup(
            panel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 400, 110, -1));

        panel_modificar.setBackground(new java.awt.Color(51, 204, 0));
        panel_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_modificarMouseExited(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar)
                .addContainerGap())
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 400, 110, -1));

        panel_mostrar.setBackground(new java.awt.Color(51, 204, 0));
        panel_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_mostrarMouseExited(evt);
            }
        });

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("Mostrar");
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout panel_mostrarLayout = new javax.swing.GroupLayout(panel_mostrar);
        panel_mostrar.setLayout(panel_mostrarLayout);
        panel_mostrarLayout.setHorizontalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mostrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_mostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrar)
                .addContainerGap())
        );
        panel_mostrarLayout.setVerticalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icono_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panel_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ingrese_idproductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_idproductoMousePressed

        if(ingrese_idproducto.getText().equals("Ingrese el ID del producto")){
            ingrese_idproducto.setText("");
            ingrese_idproducto.setForeground(Color.black);
        }

        if(ingrese_idventa. getText().isEmpty()){
            ingrese_idventa.setText("Ingrese el ID de la venta");
            ingrese_idventa.setForeground(Color.gray);
        }

        if(ingrese_subtotal. getText().isEmpty()){
            ingrese_subtotal.setText("Ingrese el subtotal del detalle");
            ingrese_subtotal.setForeground(Color.gray);
        }

        if(ingrese_detalle. getText().isEmpty()){
            ingrese_detalle.setText("Ingrese el detalle de venta");
            ingrese_detalle.setForeground(Color.gray);
        }

        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_idproductoMousePressed

    private void ingrese_idventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_idventaMousePressed

        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_idventa.getText().equals("Ingrese el ID de la venta")){
            ingrese_idventa.setText("");
            ingrese_idventa.setForeground(Color.black);
        }

        if(ingrese_subtotal. getText().isEmpty()){
            ingrese_subtotal.setText("Ingrese el subtotal del detalle");
            ingrese_subtotal.setForeground(Color.gray);
        }

        if(ingrese_detalle. getText().isEmpty()){
            ingrese_detalle.setText("Ingrese el detalle de venta");
            ingrese_detalle.setForeground(Color.gray);
        }

        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_idventaMousePressed

    private void ingrese_subtotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_subtotalMousePressed

        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_idventa. getText().isEmpty()){
            ingrese_idventa.setText("Ingrese el ID de la venta");
            ingrese_idventa.setForeground(Color.gray);
        }

        if(ingrese_subtotal.getText().equals("Ingrese el subtotal del detalle")){
            ingrese_subtotal.setText("");
            ingrese_subtotal.setForeground(Color.black);
        }

        if(ingrese_detalle. getText().isEmpty()){
            ingrese_detalle.setText("Ingrese el detalle de venta");
            ingrese_detalle.setForeground(Color.gray);
        }

        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_subtotalMousePressed

    private void ingrese_detalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_detalleMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_idventa. getText().isEmpty()){
            ingrese_idventa.setText("Ingrese el ID de la venta");
            ingrese_idventa.setForeground(Color.gray);
        }

        if(ingrese_subtotal. getText().isEmpty()){
            ingrese_subtotal.setText("Ingrese el subtotal del detalle");
            ingrese_subtotal.setForeground(Color.gray);
        }

        if(ingrese_detalle.getText().equals("Ingrese el detalle de venta")){
            ingrese_detalle.setText("");
            ingrese_detalle.setForeground(Color.black);
        }

        if(ingrese_cantidad. getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad del producto");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_detalleMousePressed

    private void ingrese_cantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_cantidadMousePressed
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese el ID del producto");
            ingrese_idproducto.setForeground(Color.gray);
        }

        if(ingrese_idventa. getText().isEmpty()){
            ingrese_idventa.setText("Ingrese el ID de la venta");
            ingrese_idventa.setForeground(Color.gray);
        }

        if(ingrese_subtotal. getText().isEmpty()){
            ingrese_subtotal.setText("Ingrese el subtotal del detalle");
            ingrese_subtotal.setForeground(Color.gray);
        }

        if(ingrese_detalle. getText().isEmpty()){
            ingrese_detalle.setText("Ingrese el detalle de venta");
            ingrese_detalle.setForeground(Color.gray);
        }

        if(ingrese_cantidad.getText().equals("Ingrese la cantidad del producto")){
            ingrese_cantidad.setText("");
            ingrese_cantidad.setForeground(Color.black);
        }
    }//GEN-LAST:event_ingrese_cantidadMousePressed

    private void ingrese_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingrese_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingrese_cantidadActionPerformed

    private void panel_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseEntered
        panel_agregar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_agregarMouseEntered

    private void panel_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseExited
        panel_agregar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_agregarMouseExited

    private void panel_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseEntered
        panel_buscar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_buscarMouseEntered

    private void panel_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_buscarMouseExited
        panel_buscar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_buscarMouseExited

    private void panel_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseEntered
        panel_modificar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_modificarMouseEntered

    private void panel_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_modificarMouseExited
        panel_modificar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_modificarMouseExited

    private void panel_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseEntered
        panel_mostrar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_mostrarMouseEntered

    private void panel_mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostrarMouseExited
        panel_mostrar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_mostrarMouseExited

    // SUBIR   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel detalle;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono_agregar;
    private javax.swing.JLabel icono_buscar;
    private javax.swing.JLabel icono_modificar;
    private javax.swing.JLabel icono_mostrar;
    private javax.swing.JLabel id_producto;
    private javax.swing.JLabel id_venta;
    private javax.swing.JTextField ingrese_cantidad;
    private javax.swing.JTextField ingrese_detalle;
    private javax.swing.JTextField ingrese_idproducto;
    private javax.swing.JTextField ingrese_idventa;
    private javax.swing.JTextField ingrese_subtotal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel mostrar;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_agrofacil;
    private javax.swing.JPanel panel_buscar;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_mostrar;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel venta;
    // End of variables declaration//GEN-END:variables
}
