/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import clases.Conexion;
import clases.Sql;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.text.DateFormat;
import javax.swing.table.DefaultTableModel;



/**
 *
 * 
 */
  public class Venta extends javax.swing.JPanel {
  private DefaultTableModel model;
  public static java.util.Date hoy = new java.util.Date();
  public static String patron = "dd/MMM/yyyy";

    public static String sfecha;
    public static DateFormat formato1;
    
    /**
     * Creates new form Principal
     */
    public Venta() {
        initComponents();
        
      //TABLA
        
        String data3[][]={};
        String col[]= {"Id" , "Cantidad" , "Total"};
        model = new DefaultTableModel(data3,col);
        tabla_venta.setModel(model);
        
        //--------------------------------------------------
        //CAMPOS NO EDITABLES
        
        fecha_ventas.setDate(hoy);
        ingrese_id.setEnabled(false);
        ingrese_cedulacliente.setEnabled(false);
        ingrese_cedulaempleado.setEnabled(false);
        ingrese_valorventa.setEnabled(false);
        

        //--------------------------------------------------
        //CARGAR EMPLEADOS
        
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query = "select * from empleado order by cedula_empleado";

            ResultSet rs = con.consultar(query);

            while (rs.next()) {
           ingrese_cedulaempleado.getText().trim();

            }

            con.cerrar();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_agrofacil = new javax.swing.JPanel();
        venta = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        cedula_empleado = new javax.swing.JLabel();
        fecha_ventas = new com.toedter.calendar.JDateChooser();
        ingrese_id = new javax.swing.JTextField();
        ingrese_cedulacliente = new javax.swing.JTextField();
        ingrese_cedulaempleado = new javax.swing.JTextField();
        ingrese_valorventa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ventas_tabla = new javax.swing.JScrollPane();
        tabla_venta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        valor_total = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        panel_agregar = new javax.swing.JPanel();
        producto = new javax.swing.JLabel();
        panel_facturar = new javax.swing.JPanel();
        facturar = new javax.swing.JLabel();
        panel_venta = new javax.swing.JPanel();
        ventas = new javax.swing.JLabel();
        panel_eliminar = new javax.swing.JPanel();
        eliminar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ingrese_idproducto = new javax.swing.JTextField();
        ingrese_cantidad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agrofacil.setBackground(new java.awt.Color(0, 204, 0));
        panel_agrofacil.setLayout(null);

        venta.setFont(new java.awt.Font("Leelawadee UI", 3, 36)); // NOI18N
        venta.setForeground(new java.awt.Color(255, 255, 255));
        venta.setText("VENTA IDENTIFICADOR");
        panel_agrofacil.add(venta);
        venta.setBounds(170, 30, 420, 48);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_login1.png"))); // NOI18N
        panel_agrofacil.add(icono);
        icono.setBounds(680, 10, 107, 95);

        add(panel_agrofacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        id.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        id.setText("ID DE VENTA");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        fecha.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        fecha.setText("FECHA QUE SE REALIZO LA VENTA");
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        cedula.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cedula.setText("CEDULA DEL CLIENTE");
        add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 190, 30));

        valor.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        valor.setText("VALOR DE LA VENTA");
        add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        cedula_empleado.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cedula_empleado.setText("CEDULA DEL EMPLEADO");
        add(cedula_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 210, 30));
        add(fecha_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, 30));

        ingrese_id.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_id.setText("Ingrese el ID de la venta");
        ingrese_id.setBorder(null);
        ingrese_id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingrese_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_idMousePressed(evt);
            }
        });
        add(ingrese_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));

        ingrese_cedulacliente.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
        ingrese_cedulacliente.setBorder(null);
        ingrese_cedulacliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingrese_cedulacliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_cedulaclienteMousePressed(evt);
            }
        });
        ingrese_cedulacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingrese_cedulaclienteActionPerformed(evt);
            }
        });
        add(ingrese_cedulacliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 170, 20));

        ingrese_cedulaempleado.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_cedulaempleado.setText("Ingrese la cedula empleado");
        ingrese_cedulaempleado.setBorder(null);
        ingrese_cedulaempleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingrese_cedulaempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_cedulaempleadoMousePressed(evt);
            }
        });
        add(ingrese_cedulaempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 160, 30));

        ingrese_valorventa.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_valorventa.setText("Ingrese el valor total de la venta");
        ingrese_valorventa.setBorder(null);
        ingrese_valorventa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingrese_valorventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_valorventaMousePressed(evt);
            }
        });
        add(ingrese_valorventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 210, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 230, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 10));

        tabla_venta.setBackground(new java.awt.Color(204, 204, 204));
        tabla_venta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tabla_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID de venta", "Cedula cliente", "Cedula empleado ", "Valor de venta", "ID de producto", "Cantidad", "Fecha de venta"
            }
        ));
        tabla_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ventas_tabla.setViewportView(tabla_venta);

        add(ventas_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 700, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor total:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, 40));

        valor_total.setBackground(new java.awt.Color(51, 51, 255));

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0.0");

        javax.swing.GroupLayout valor_totalLayout = new javax.swing.GroupLayout(valor_total);
        valor_total.setLayout(valor_totalLayout);
        valor_totalLayout.setHorizontalGroup(
            valor_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        valor_totalLayout.setVerticalGroup(
            valor_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 100, 50));

        panel_agregar.setBackground(new java.awt.Color(51, 204, 0));
        panel_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_agregarMouseExited(evt);
            }
        });

        producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setText("agregar producto");

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(producto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(producto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 130, 40));

        panel_facturar.setBackground(new java.awt.Color(51, 204, 0));
        panel_facturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_facturarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_facturarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_facturarMouseExited(evt);
            }
        });

        facturar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        facturar.setForeground(new java.awt.Color(255, 255, 255));
        facturar.setText(" Facturar");

        javax.swing.GroupLayout panel_facturarLayout = new javax.swing.GroupLayout(panel_facturar);
        panel_facturar.setLayout(panel_facturarLayout);
        panel_facturarLayout.setHorizontalGroup(
            panel_facturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_facturarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facturar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_facturarLayout.setVerticalGroup(
            panel_facturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facturar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(panel_facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 80, -1));

        panel_venta.setBackground(new java.awt.Color(51, 204, 0));
        panel_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_ventaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ventaMouseExited(evt);
            }
        });

        ventas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ventas.setForeground(new java.awt.Color(255, 255, 255));
        ventas.setText(" Nueva venta");

        javax.swing.GroupLayout panel_ventaLayout = new javax.swing.GroupLayout(panel_venta);
        panel_venta.setLayout(panel_ventaLayout);
        panel_ventaLayout.setHorizontalGroup(
            panel_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ventaLayout.setVerticalGroup(
            panel_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(panel_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 100, -1));

        panel_eliminar.setBackground(new java.awt.Color(51, 204, 0));
        panel_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_eliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_eliminarMouseExited(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar producto");

        javax.swing.GroupLayout panel_eliminarLayout = new javax.swing.GroupLayout(panel_eliminar);
        panel_eliminar.setLayout(panel_eliminarLayout);
        panel_eliminarLayout.setHorizontalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_eliminarLayout.setVerticalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(panel_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 140, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setText("ID DE PRODUCTO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel3.setText("CANTIDAD");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        ingrese_idproducto.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_idproducto.setText("Ingrese ID producto");
        ingrese_idproducto.setBorder(null);
        ingrese_idproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingrese_idproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_idproductoMousePressed(evt);
            }
        });
        add(ingrese_idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 30));

        ingrese_cantidad.setForeground(new java.awt.Color(153, 153, 153));
        ingrese_cantidad.setText("Ingrese la cantidad");
        ingrese_cantidad.setBorder(null);
        ingrese_cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingrese_cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingrese_cantidadMousePressed(evt);
            }
        });
        add(ingrese_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 220, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void ingrese_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_idMousePressed
        if(ingrese_id.getText().equals("Ingrese el ID de la venta")){
            ingrese_id.setText("");
            ingrese_id.setForeground(Color.black);
        }

        if(ingrese_cedulacliente. getText().isEmpty()){
            ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
            ingrese_cedulacliente.setForeground(Color.gray);
        }

        if(ingrese_cedulaempleado. getText().isEmpty()){
            ingrese_cedulaempleado.setText("Ingrese la cedula empleado");
            ingrese_cedulaempleado.setForeground(Color.gray);
        }

        if(ingrese_valorventa. getText().isEmpty()){
            ingrese_valorventa.setText("Ingrese el valor total de la venta");
            ingrese_valorventa.setForeground(Color.gray);
        }
        
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese ID producto");
            ingrese_idproducto.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_idMousePressed

    private void ingrese_cedulaclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_cedulaclienteMousePressed

        if(ingrese_id. getText().isEmpty()){
            ingrese_id.setText("Ingrese el ID de la venta");
            ingrese_id.setForeground(Color.gray);
        }

        if(ingrese_cedulacliente.getText().equals("Ingrese la cedula del cliente")){
            ingrese_cedulacliente.setText("");
            ingrese_cedulacliente.setForeground(Color.black);
        }

        if(ingrese_cedulaempleado. getText().isEmpty()){
            ingrese_cedulaempleado.setText("Ingrese la cedula empleado");
            ingrese_cedulaempleado.setForeground(Color.gray);
        }

        if(ingrese_valorventa. getText().isEmpty()){
            ingrese_valorventa.setText("Ingrese el valor total de la venta");
            ingrese_valorventa.setForeground(Color.gray);
        }
        
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese ID producto");
            ingrese_idproducto.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_cedulaclienteMousePressed

    private void ingrese_cedulaempleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_cedulaempleadoMousePressed
        if(ingrese_id. getText().isEmpty()){
            ingrese_id.setText("Ingrese el ID de la venta");
            ingrese_id.setForeground(Color.gray);
        }

        if(ingrese_cedulacliente. getText().isEmpty()){
            ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
            ingrese_cedulacliente.setForeground(Color.gray);
        }

        if(ingrese_cedulaempleado.getText().equals("Ingrese la cedula empleado")){
            ingrese_cedulaempleado.setText("");
            ingrese_cedulaempleado.setForeground(Color.black);
        }

        if(ingrese_valorventa. getText().isEmpty()){
            ingrese_valorventa.setText("Ingrese el valor total de la venta");
            ingrese_valorventa.setForeground(Color.gray);
        }
        
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese ID producto");
            ingrese_idproducto.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_cedulaempleadoMousePressed

    private void ingrese_valorventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_valorventaMousePressed
        if(ingrese_id. getText().isEmpty()){
            ingrese_id.setText("Ingrese el ID de la venta");
            ingrese_id.setForeground(Color.gray);
        }

        if(ingrese_cedulacliente. getText().isEmpty()){
            ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
            ingrese_cedulacliente.setForeground(Color.gray);
        }

        if(ingrese_cedulaempleado. getText().isEmpty()){
            ingrese_cedulaempleado.setText("Ingrese cedula empleado");
            ingrese_cedulaempleado.setForeground(Color.gray);
        }

        if(ingrese_valorventa.getText().equals("Ingrese el valor total de la venta")){
            ingrese_valorventa.setText("");
            ingrese_valorventa.setForeground(Color.black);
        }
        
        if(ingrese_idproducto. getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese ID producto");
            ingrese_idproducto.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_valorventaMousePressed

    private void panel_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseEntered
        panel_agregar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_agregarMouseEntered

    private void panel_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseExited
        panel_agregar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_agregarMouseExited

    private void panel_facturarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_facturarMouseClicked
       
    }//GEN-LAST:event_panel_facturarMouseClicked

    private void panel_facturarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_facturarMouseEntered
         panel_facturar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_facturarMouseEntered

    private void panel_facturarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_facturarMouseExited
        panel_facturar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_facturarMouseExited

    private void panel_ventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ventaMouseEntered
        panel_venta.setBackground(Color.orange);
    }//GEN-LAST:event_panel_ventaMouseEntered

    private void panel_ventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ventaMouseExited
        panel_venta.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_ventaMouseExited

    private void panel_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_eliminarMouseEntered
        panel_eliminar.setBackground(Color.orange);
    }//GEN-LAST:event_panel_eliminarMouseEntered

    private void panel_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_eliminarMouseExited
        panel_eliminar.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_panel_eliminarMouseExited

    private void panel_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_agregarMouseClicked
        
        if(ingrese_idproducto.getText().equals("Ingrese ID producto") || ingrese_idproducto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese el ID del producto");
        }
        else{
            if(ingrese_cantidad.getText().equals("Ingrese la cantidad") || ingrese_cantidad.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad del producto");
            }
            else{
                int con1 = 0;
                Conexion con = new Conexion();
                con.ConexionPostgres();
                
                String query = "SELECT * FROM producto WHERE "
            }
        }
    }//GEN-LAST:event_panel_agregarMouseClicked

    private void panel_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ventaMouseClicked
      ingrese_cedulaempleado.setEnabled(true);
    
      for (int i = 0; i< tabla_venta.getRowCount(); i++){
          model.removeRow(i);
      }
      ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
      ingrese_cedulaempleado.setText("Ingrese la cedula del empleado");
      ingrese_idproducto.setText("Ingrese ID producto");
      ingrese_cantidad.setText("Ingrese la cantidad");
      total.setText("0.0");
      
      Sql s = new Sql();
      int id = s.id_incrementable();
      String idv = String.valueOf(id);
      ingrese_id.setText(idv);
    }//GEN-LAST:event_panel_ventaMouseClicked

    private void panel_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_eliminarMouseClicked
   
    }//GEN-LAST:event_panel_eliminarMouseClicked

    private void ingrese_cedulaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingrese_cedulaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingrese_cedulaclienteActionPerformed

    
    
    private void ingrese_idproductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_idproductoMousePressed
         if(ingrese_id. getText().isEmpty()){
            ingrese_id.setText("Ingrese el ID de la venta");
            ingrese_id.setForeground(Color.gray);
        }

        if(ingrese_cedulacliente. getText().isEmpty()){
            ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
            ingrese_cedulacliente.setForeground(Color.gray);
        }

        if(ingrese_cedulaempleado. getText().isEmpty()){
            ingrese_cedulaempleado.setText("Ingrese cedula empleado");
            ingrese_cedulaempleado.setForeground(Color.gray);
        }

        if(ingrese_valorventa.getText().isEmpty()){
            ingrese_valorventa.setText("Ingrese el valor total de la venta");
            ingrese_valorventa.setForeground(Color.gray);
        }
        
        if(ingrese_idproducto.getText().equals("Ingrese ID producto")){
            ingrese_idproducto.setText("");
            ingrese_idproducto.setForeground(Color.black);
        }
        
        if(ingrese_cantidad.getText().isEmpty()){
            ingrese_cantidad.setText("Ingrese la cantidad");
            ingrese_cantidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingrese_idproductoMousePressed

    private void ingrese_cantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrese_cantidadMousePressed
        if(ingrese_id. getText().isEmpty()){
            ingrese_id.setText("Ingrese el ID de la venta");
            ingrese_id.setForeground(Color.gray);
        }

        if(ingrese_cedulacliente. getText().isEmpty()){
            ingrese_cedulacliente.setText("Ingrese la cedula del cliente");
            ingrese_cedulacliente.setForeground(Color.gray);
        }

        if(ingrese_cedulaempleado. getText().isEmpty()){
            ingrese_cedulaempleado.setText("Ingrese cedula empleado");
            ingrese_cedulaempleado.setForeground(Color.gray);
        }

        if(ingrese_valorventa.getText().isEmpty()){
            ingrese_valorventa.setText("Ingrese el valor total de la venta");
            ingrese_valorventa.setForeground(Color.gray);
        }
        
        if(ingrese_idproducto.getText().isEmpty()){
            ingrese_idproducto.setText("Ingrese ID producto");
            ingrese_idproducto.setForeground(Color.gray);
        }
        
        if(ingrese_cantidad.getText().equals("Ingrese la cantidad")){
            ingrese_cantidad.setText("");
            ingrese_cantidad.setForeground(Color.black);
        }
    }//GEN-LAST:event_ingrese_cantidadMousePressed

    
    
    
    // SUBIR   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel cedula_empleado;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel facturar;
    private javax.swing.JLabel fecha;
    private com.toedter.calendar.JDateChooser fecha_ventas;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel id;
    private javax.swing.JTextField ingrese_cantidad;
    private javax.swing.JTextField ingrese_cedulacliente;
    private javax.swing.JTextField ingrese_cedulaempleado;
    private javax.swing.JTextField ingrese_id;
    private javax.swing.JTextField ingrese_idproducto;
    private javax.swing.JTextField ingrese_valorventa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_agrofacil;
    private javax.swing.JPanel panel_eliminar;
    private javax.swing.JPanel panel_facturar;
    private javax.swing.JPanel panel_venta;
    private javax.swing.JLabel producto;
    private javax.swing.JTable tabla_venta;
    private javax.swing.JLabel total;
    private javax.swing.JLabel valor;
    private javax.swing.JPanel valor_total;
    private javax.swing.JLabel venta;
    private javax.swing.JLabel ventas;
    private javax.swing.JScrollPane ventas_tabla;
    // End of variables declaration//GEN-END:variables
}
